[tool.poetry]
name = "hsdlib"
version = "0.1.0"
description = "Python environment for Hsdlib"
authors = ["Hassan Abedi <hassan.abedi.t+hsdlib@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
