name: Run Benchmarks (AArch64)

on:
  workflow_dispatch:  # Allow manual runs
  push:
    tags:
      - 'v*'  # Trigger on version tags

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04-arm # Or `ubuntu-22.04-arm`

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show CPU specs
        run: |
          echo "=== CPU Model ==="
          grep -m1 'model name' /proc/cpuinfo | cut -d':' -f2 | xargs
          echo "=== CPU Cores ==="
          nproc
          echo "=== Full lscpu Dump ==="
          lscpu

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make install-deps

      - name: Run Benchmarks for AArch64
        run: make bench-aarch64
