name: Publish HsdPy to PyPI

on:
  workflow_dispatch:  # Allow manual runs
  push:
    tags:
      - 'v*'  # Trigger on version tags

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make install-deps

      - name: Run Tests for HsdPy
        run: |
          make python-install
          make python-tests

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
