name: Run Tests (Linux; AArch64)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build-aarch64:
    runs-on: ubuntu-24.04-arm # Or `ubuntu-22.04-arm`
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make install-deps

      - name: Run AArch64 Tests
        run: |
          set -e
          make test-aarch64 > full_test_log.log 2>&1 || echo $? > .exit_code

          echo "::group::Test Log Output"
          cat full_test_log.log
          echo "::endgroup::"

          if [ -f .exit_code ]; then
            echo "Tests failed with exit code $(cat .exit_code)"
            exit $(cat .exit_code)
          fi

