name: Run Tests (Makefile; Linux; AMD64)

on:
  workflow_dispatch:  # Allow manual runs
  push:
    tags:
      - 'v*'  # Trigger on version tags

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make bash
          make install-deps

      - name: Run Tests for Makefile
        run: |
          bash test_makefile.sh

